wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1652687307
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      4: 3.9.0
      5: 0.12.16
      8:
      - 3
      - 5
